#ifndef VIDEOS_H_INCLUDED
#define VIDEOS_H_INCLUDED

char Intro[500][40] =
{
    {"Video\\Intro\\pacman000.bmp"},
{"Video\\Intro\\pacman001.bmp"}, {"Video\\Intro\\pacman002.bmp"}, {"Video\\Intro\\pacman003.bmp"}, {"Video\\Intro\\pacman004.bmp"}, {"Video\\Intro\\pacman005.bmp"}, {"Video\\Intro\\pacman006.bmp"}, {"Video\\Intro\\pacman007.bmp"}, {"Video\\Intro\\pacman008.bmp"}, {"Video\\Intro\\pacman009.bmp"}, {"Video\\Intro\\pacman010.bmp"},
{"Video\\Intro\\pacman011.bmp"}, {"Video\\Intro\\pacman012.bmp"}, {"Video\\Intro\\pacman013.bmp"}, {"Video\\Intro\\pacman014.bmp"}, {"Video\\Intro\\pacman015.bmp"}, {"Video\\Intro\\pacman016.bmp"}, {"Video\\Intro\\pacman017.bmp"}, {"Video\\Intro\\pacman018.bmp"}, {"Video\\Intro\\pacman019.bmp"}, {"Video\\Intro\\pacman020.bmp"},
{"Video\\Intro\\pacman021.bmp"}, {"Video\\Intro\\pacman022.bmp"}, {"Video\\Intro\\pacman023.bmp"}, {"Video\\Intro\\pacman024.bmp"}, {"Video\\Intro\\pacman025.bmp"}, {"Video\\Intro\\pacman026.bmp"}, {"Video\\Intro\\pacman027.bmp"}, {"Video\\Intro\\pacman028.bmp"}, {"Video\\Intro\\pacman029.bmp"}, {"Video\\Intro\\pacman030.bmp"},
{"Video\\Intro\\pacman031.bmp"}, {"Video\\Intro\\pacman032.bmp"}, {"Video\\Intro\\pacman033.bmp"}, {"Video\\Intro\\pacman034.bmp"}, {"Video\\Intro\\pacman035.bmp"}, {"Video\\Intro\\pacman036.bmp"}, {"Video\\Intro\\pacman037.bmp"}, {"Video\\Intro\\pacman038.bmp"}, {"Video\\Intro\\pacman039.bmp"}, {"Video\\Intro\\pacman040.bmp"},
{"Video\\Intro\\pacman041.bmp"}, {"Video\\Intro\\pacman042.bmp"}, {"Video\\Intro\\pacman043.bmp"}, {"Video\\Intro\\pacman044.bmp"}, {"Video\\Intro\\pacman045.bmp"}, {"Video\\Intro\\pacman046.bmp"}, {"Video\\Intro\\pacman047.bmp"}, {"Video\\Intro\\pacman048.bmp"}, {"Video\\Intro\\pacman049.bmp"}, {"Video\\Intro\\pacman050.bmp"},
{"Video\\Intro\\pacman051.bmp"}, {"Video\\Intro\\pacman052.bmp"}, {"Video\\Intro\\pacman053.bmp"}, {"Video\\Intro\\pacman054.bmp"}, {"Video\\Intro\\pacman055.bmp"}, {"Video\\Intro\\pacman056.bmp"}, {"Video\\Intro\\pacman057.bmp"}, {"Video\\Intro\\pacman058.bmp"}, {"Video\\Intro\\pacman059.bmp"}, {"Video\\Intro\\pacman060.bmp"},
{"Video\\Intro\\pacman061.bmp"}, {"Video\\Intro\\pacman062.bmp"}, {"Video\\Intro\\pacman063.bmp"}, {"Video\\Intro\\pacman064.bmp"}, {"Video\\Intro\\pacman065.bmp"}, {"Video\\Intro\\pacman066.bmp"}, {"Video\\Intro\\pacman067.bmp"}, {"Video\\Intro\\pacman068.bmp"}, {"Video\\Intro\\pacman069.bmp"}, {"Video\\Intro\\pacman070.bmp"},
{"Video\\Intro\\pacman071.bmp"}, {"Video\\Intro\\pacman072.bmp"}, {"Video\\Intro\\pacman073.bmp"}, {"Video\\Intro\\pacman074.bmp"}, {"Video\\Intro\\pacman075.bmp"}, {"Video\\Intro\\pacman076.bmp"}, {"Video\\Intro\\pacman077.bmp"}, {"Video\\Intro\\pacman078.bmp"}, {"Video\\Intro\\pacman079.bmp"}, {"Video\\Intro\\pacman080.bmp"},
{"Video\\Intro\\pacman081.bmp"}, {"Video\\Intro\\pacman082.bmp"}, {"Video\\Intro\\pacman083.bmp"}, {"Video\\Intro\\pacman084.bmp"}, {"Video\\Intro\\pacman085.bmp"}, {"Video\\Intro\\pacman086.bmp"}, {"Video\\Intro\\pacman087.bmp"}, {"Video\\Intro\\pacman088.bmp"}, {"Video\\Intro\\pacman089.bmp"}, {"Video\\Intro\\pacman090.bmp"},
{"Video\\Intro\\pacman091.bmp"}, {"Video\\Intro\\pacman092.bmp"}, {"Video\\Intro\\pacman093.bmp"}, {"Video\\Intro\\pacman094.bmp"}, {"Video\\Intro\\pacman095.bmp"}, {"Video\\Intro\\pacman096.bmp"}, {"Video\\Intro\\pacman097.bmp"}, {"Video\\Intro\\pacman098.bmp"}, {"Video\\Intro\\pacman099.bmp"}, {"Video\\Intro\\pacman100.bmp"},
{"Video\\Intro\\pacman101.bmp"}, {"Video\\Intro\\pacman102.bmp"}, {"Video\\Intro\\pacman103.bmp"}, {"Video\\Intro\\pacman104.bmp"}, {"Video\\Intro\\pacman105.bmp"}, {"Video\\Intro\\pacman106.bmp"}, {"Video\\Intro\\pacman107.bmp"}, {"Video\\Intro\\pacman108.bmp"}, {"Video\\Intro\\pacman109.bmp"}, {"Video\\Intro\\pacman110.bmp"},
{"Video\\Intro\\pacman111.bmp"}, {"Video\\Intro\\pacman112.bmp"}, {"Video\\Intro\\pacman113.bmp"}, {"Video\\Intro\\pacman114.bmp"}, {"Video\\Intro\\pacman115.bmp"}, {"Video\\Intro\\pacman116.bmp"}, {"Video\\Intro\\pacman117.bmp"}, {"Video\\Intro\\pacman118.bmp"}, {"Video\\Intro\\pacman119.bmp"}, {"Video\\Intro\\pacman120.bmp"},
{"Video\\Intro\\pacman121.bmp"}, {"Video\\Intro\\pacman122.bmp"}, {"Video\\Intro\\pacman123.bmp"}, {"Video\\Intro\\pacman124.bmp"}, {"Video\\Intro\\pacman125.bmp"}, {"Video\\Intro\\pacman126.bmp"}, {"Video\\Intro\\pacman127.bmp"}, {"Video\\Intro\\pacman128.bmp"}, {"Video\\Intro\\pacman129.bmp"}, {"Video\\Intro\\pacman130.bmp"},
{"Video\\Intro\\pacman131.bmp"}, {"Video\\Intro\\pacman132.bmp"}, {"Video\\Intro\\pacman133.bmp"}, {"Video\\Intro\\pacman134.bmp"}, {"Video\\Intro\\pacman135.bmp"}, {"Video\\Intro\\pacman136.bmp"}, {"Video\\Intro\\pacman137.bmp"}, {"Video\\Intro\\pacman138.bmp"}, {"Video\\Intro\\pacman139.bmp"}, {"Video\\Intro\\pacman140.bmp"},
{"Video\\Intro\\pacman141.bmp"}, {"Video\\Intro\\pacman142.bmp"}, {"Video\\Intro\\pacman143.bmp"}, {"Video\\Intro\\pacman144.bmp"}, {"Video\\Intro\\pacman145.bmp"}, {"Video\\Intro\\pacman146.bmp"}, {"Video\\Intro\\pacman147.bmp"}, {"Video\\Intro\\pacman148.bmp"}, {"Video\\Intro\\pacman149.bmp"}, {"Video\\Intro\\pacman150.bmp"},
{"Video\\Intro\\pacman151.bmp"}, {"Video\\Intro\\pacman152.bmp"}, {"Video\\Intro\\pacman153.bmp"}, {"Video\\Intro\\pacman154.bmp"}, {"Video\\Intro\\pacman155.bmp"}, {"Video\\Intro\\pacman156.bmp"}, {"Video\\Intro\\pacman157.bmp"}, {"Video\\Intro\\pacman158.bmp"}, {"Video\\Intro\\pacman159.bmp"}, {"Video\\Intro\\pacman160.bmp"},
{"Video\\Intro\\pacman161.bmp"}, {"Video\\Intro\\pacman162.bmp"}, {"Video\\Intro\\pacman163.bmp"}, {"Video\\Intro\\pacman164.bmp"}, {"Video\\Intro\\pacman165.bmp"}, {"Video\\Intro\\pacman166.bmp"}, {"Video\\Intro\\pacman167.bmp"}, {"Video\\Intro\\pacman168.bmp"}, {"Video\\Intro\\pacman169.bmp"}, {"Video\\Intro\\pacman170.bmp"},
{"Video\\Intro\\pacman171.bmp"}, {"Video\\Intro\\pacman172.bmp"}, {"Video\\Intro\\pacman173.bmp"}, {"Video\\Intro\\pacman174.bmp"}, {"Video\\Intro\\pacman175.bmp"}, {"Video\\Intro\\pacman176.bmp"}, {"Video\\Intro\\pacman177.bmp"}, {"Video\\Intro\\pacman178.bmp"}, {"Video\\Intro\\pacman179.bmp"}, {"Video\\Intro\\pacman180.bmp"},
{"Video\\Intro\\pacman181.bmp"}, {"Video\\Intro\\pacman182.bmp"}, {"Video\\Intro\\pacman183.bmp"}, {"Video\\Intro\\pacman184.bmp"}, {"Video\\Intro\\pacman185.bmp"}, {"Video\\Intro\\pacman186.bmp"}, {"Video\\Intro\\pacman187.bmp"}, {"Video\\Intro\\pacman188.bmp"}, {"Video\\Intro\\pacman189.bmp"}, {"Video\\Intro\\pacman190.bmp"},
{"Video\\Intro\\pacman191.bmp"}, {"Video\\Intro\\pacman192.bmp"}, {"Video\\Intro\\pacman193.bmp"}, {"Video\\Intro\\pacman194.bmp"}, {"Video\\Intro\\pacman195.bmp"}, {"Video\\Intro\\pacman196.bmp"}, {"Video\\Intro\\pacman197.bmp"}, {"Video\\Intro\\pacman198.bmp"}, {"Video\\Intro\\pacman199.bmp"}, {"Video\\Intro\\pacman200.bmp"},
{"Video\\Intro\\pacman201.bmp"}, {"Video\\Intro\\pacman202.bmp"}, {"Video\\Intro\\pacman203.bmp"}, {"Video\\Intro\\pacman204.bmp"}, {"Video\\Intro\\pacman205.bmp"}, {"Video\\Intro\\pacman206.bmp"}, {"Video\\Intro\\pacman207.bmp"}, {"Video\\Intro\\pacman208.bmp"}, {"Video\\Intro\\pacman209.bmp"}, {"Video\\Intro\\pacman210.bmp"},
{"Video\\Intro\\pacman211.bmp"}, {"Video\\Intro\\pacman212.bmp"}, {"Video\\Intro\\pacman213.bmp"}, {"Video\\Intro\\pacman214.bmp"}, {"Video\\Intro\\pacman215.bmp"}, {"Video\\Intro\\pacman216.bmp"}, {"Video\\Intro\\pacman217.bmp"}, {"Video\\Intro\\pacman218.bmp"}, {"Video\\Intro\\pacman219.bmp"}, {"Video\\Intro\\pacman220.bmp"},
{"Video\\Intro\\pacman221.bmp"}, {"Video\\Intro\\pacman222.bmp"}, {"Video\\Intro\\pacman223.bmp"}, {"Video\\Intro\\pacman224.bmp"}, {"Video\\Intro\\pacman225.bmp"}, {"Video\\Intro\\pacman226.bmp"}, {"Video\\Intro\\pacman227.bmp"}, {"Video\\Intro\\pacman228.bmp"}, {"Video\\Intro\\pacman229.bmp"}, {"Video\\Intro\\pacman230.bmp"},
{"Video\\Intro\\pacman231.bmp"}, {"Video\\Intro\\pacman232.bmp"}, {"Video\\Intro\\pacman233.bmp"}, {"Video\\Intro\\pacman234.bmp"}, {"Video\\Intro\\pacman235.bmp"}, {"Video\\Intro\\pacman236.bmp"}, {"Video\\Intro\\pacman237.bmp"}, {"Video\\Intro\\pacman238.bmp"}, {"Video\\Intro\\pacman239.bmp"}, {"Video\\Intro\\pacman240.bmp"},
{"Video\\Intro\\pacman241.bmp"}, {"Video\\Intro\\pacman242.bmp"}, {"Video\\Intro\\pacman243.bmp"}, {"Video\\Intro\\pacman244.bmp"}, {"Video\\Intro\\pacman245.bmp"}, {"Video\\Intro\\pacman246.bmp"}, {"Video\\Intro\\pacman247.bmp"}, {"Video\\Intro\\pacman248.bmp"}, {"Video\\Intro\\pacman249.bmp"}, {"Video\\Intro\\pacman250.bmp"},
{"Video\\Intro\\pacman251.bmp"}, {"Video\\Intro\\pacman252.bmp"}, {"Video\\Intro\\pacman253.bmp"}, {"Video\\Intro\\pacman254.bmp"}, {"Video\\Intro\\pacman255.bmp"}, {"Video\\Intro\\pacman256.bmp"}, {"Video\\Intro\\pacman257.bmp"}, {"Video\\Intro\\pacman258.bmp"}, {"Video\\Intro\\pacman259.bmp"}, {"Video\\Intro\\pacman260.bmp"},
{"Video\\Intro\\pacman261.bmp"}, {"Video\\Intro\\pacman262.bmp"}, {"Video\\Intro\\pacman263.bmp"}, {"Video\\Intro\\pacman264.bmp"}, {"Video\\Intro\\pacman265.bmp"}, {"Video\\Intro\\pacman266.bmp"}, {"Video\\Intro\\pacman267.bmp"}, {"Video\\Intro\\pacman268.bmp"}, {"Video\\Intro\\pacman269.bmp"}, {"Video\\Intro\\pacman270.bmp"},
{"Video\\Intro\\pacman271.bmp"}, {"Video\\Intro\\pacman272.bmp"}, {"Video\\Intro\\pacman273.bmp"}, {"Video\\Intro\\pacman274.bmp"}, {"Video\\Intro\\pacman275.bmp"}, {"Video\\Intro\\pacman276.bmp"}, {"Video\\Intro\\pacman277.bmp"}, {"Video\\Intro\\pacman278.bmp"}, {"Video\\Intro\\pacman279.bmp"}, {"Video\\Intro\\pacman280.bmp"},
{"Video\\Intro\\pacman281.bmp"}, {"Video\\Intro\\pacman282.bmp"}, {"Video\\Intro\\pacman283.bmp"}, {"Video\\Intro\\pacman284.bmp"}, {"Video\\Intro\\pacman285.bmp"}, {"Video\\Intro\\pacman286.bmp"}, {"Video\\Intro\\pacman287.bmp"}, {"Video\\Intro\\pacman288.bmp"}, {"Video\\Intro\\pacman289.bmp"}, {"Video\\Intro\\pacman290.bmp"},
{"Video\\Intro\\pacman291.bmp"}, {"Video\\Intro\\pacman292.bmp"}, {"Video\\Intro\\pacman293.bmp"}, {"Video\\Intro\\pacman294.bmp"}, {"Video\\Intro\\pacman295.bmp"}, {"Video\\Intro\\pacman296.bmp"}, {"Video\\Intro\\pacman297.bmp"}, {"Video\\Intro\\pacman298.bmp"}, {"Video\\Intro\\pacman299.bmp"}, {"Video\\Intro\\pacman300.bmp"},
{"Video\\Intro\\pacman301.bmp"}, {"Video\\Intro\\pacman302.bmp"}, {"Video\\Intro\\pacman303.bmp"}, {"Video\\Intro\\pacman304.bmp"}, {"Video\\Intro\\pacman305.bmp"}, {"Video\\Intro\\pacman306.bmp"}, {"Video\\Intro\\pacman307.bmp"}, {"Video\\Intro\\pacman308.bmp"}, {"Video\\Intro\\pacman309.bmp"}, {"Video\\Intro\\pacman310.bmp"},
{"Video\\Intro\\pacman311.bmp"}, {"Video\\Intro\\pacman312.bmp"}, {"Video\\Intro\\pacman313.bmp"}, {"Video\\Intro\\pacman314.bmp"}, {"Video\\Intro\\pacman315.bmp"}, {"Video\\Intro\\pacman316.bmp"}, {"Video\\Intro\\pacman317.bmp"}, {"Video\\Intro\\pacman318.bmp"}, {"Video\\Intro\\pacman319.bmp"}, {"Video\\Intro\\pacman320.bmp"},
{"Video\\Intro\\pacman321.bmp"}, {"Video\\Intro\\pacman322.bmp"}, {"Video\\Intro\\pacman323.bmp"}, {"Video\\Intro\\pacman324.bmp"}, {"Video\\Intro\\pacman325.bmp"}, {"Video\\Intro\\pacman326.bmp"}, {"Video\\Intro\\pacman327.bmp"}, {"Video\\Intro\\pacman328.bmp"}, {"Video\\Intro\\pacman329.bmp"}, {"Video\\Intro\\pacman330.bmp"},
{"Video\\Intro\\pacman331.bmp"}, {"Video\\Intro\\pacman332.bmp"}, {"Video\\Intro\\pacman333.bmp"}, {"Video\\Intro\\pacman334.bmp"}, {"Video\\Intro\\pacman335.bmp"}, {"Video\\Intro\\pacman336.bmp"}, {"Video\\Intro\\pacman337.bmp"}, {"Video\\Intro\\pacman338.bmp"}, {"Video\\Intro\\pacman339.bmp"}, {"Video\\Intro\\pacman340.bmp"},
{"Video\\Intro\\pacman341.bmp"}, {"Video\\Intro\\pacman342.bmp"}, {"Video\\Intro\\pacman343.bmp"}, {"Video\\Intro\\pacman344.bmp"}, {"Video\\Intro\\pacman345.bmp"}, {"Video\\Intro\\pacman346.bmp"}, {"Video\\Intro\\pacman347.bmp"}, {"Video\\Intro\\pacman348.bmp"}, {"Video\\Intro\\pacman349.bmp"}, {"Video\\Intro\\pacman350.bmp"},
{"Video\\Intro\\pacman351.bmp"}, {"Video\\Intro\\pacman352.bmp"}, {"Video\\Intro\\pacman353.bmp"}, {"Video\\Intro\\pacman354.bmp"}, {"Video\\Intro\\pacman355.bmp"}, {"Video\\Intro\\pacman356.bmp"}, {"Video\\Intro\\pacman357.bmp"}, {"Video\\Intro\\pacman358.bmp"}, {"Video\\Intro\\pacman359.bmp"}, {"Video\\Intro\\pacman360.bmp"},
{"Video\\Intro\\pacman361.bmp"}, {"Video\\Intro\\pacman362.bmp"}, {"Video\\Intro\\pacman363.bmp"}, {"Video\\Intro\\pacman364.bmp"}, {"Video\\Intro\\pacman365.bmp"}, {"Video\\Intro\\pacman366.bmp"}, {"Video\\Intro\\pacman367.bmp"}, {"Video\\Intro\\pacman368.bmp"}, {"Video\\Intro\\pacman369.bmp"}, {"Video\\Intro\\pacman370.bmp"},
{"Video\\Intro\\pacman371.bmp"}, {"Video\\Intro\\pacman372.bmp"}, {"Video\\Intro\\pacman373.bmp"}, {"Video\\Intro\\pacman374.bmp"}, {"Video\\Intro\\pacman375.bmp"}, {"Video\\Intro\\pacman376.bmp"}, {"Video\\Intro\\pacman377.bmp"}, {"Video\\Intro\\pacman378.bmp"}, {"Video\\Intro\\pacman379.bmp"}, {"Video\\Intro\\pacman380.bmp"},
{"Video\\Intro\\pacman381.bmp"}, {"Video\\Intro\\pacman382.bmp"}, {"Video\\Intro\\pacman383.bmp"}, {"Video\\Intro\\pacman384.bmp"}, {"Video\\Intro\\pacman385.bmp"}, {"Video\\Intro\\pacman386.bmp"}, {"Video\\Intro\\pacman387.bmp"}, {"Video\\Intro\\pacman388.bmp"}, {"Video\\Intro\\pacman389.bmp"}, {"Video\\Intro\\pacman390.bmp"},
{"Video\\Intro\\pacman391.bmp"}, {"Video\\Intro\\pacman392.bmp"}, {"Video\\Intro\\pacman393.bmp"}, {"Video\\Intro\\pacman394.bmp"}, {"Video\\Intro\\pacman395.bmp"}, {"Video\\Intro\\pacman396.bmp"}, {"Video\\Intro\\pacman397.bmp"}, {"Video\\Intro\\pacman398.bmp"}, {"Video\\Intro\\pacman399.bmp"}, {"Video\\Intro\\pacman400.bmp"},
{"Video\\Intro\\pacman401.bmp"}, {"Video\\Intro\\pacman402.bmp"}, {"Video\\Intro\\pacman403.bmp"}, {"Video\\Intro\\pacman404.bmp"}, {"Video\\Intro\\pacman405.bmp"}, {"Video\\Intro\\pacman406.bmp"}, {"Video\\Intro\\pacman407.bmp"}, {"Video\\Intro\\pacman408.bmp"}, {"Video\\Intro\\pacman409.bmp"}, {"Video\\Intro\\pacman410.bmp"},
{"Video\\Intro\\pacman411.bmp"}, {"Video\\Intro\\pacman412.bmp"}, {"Video\\Intro\\pacman413.bmp"}, {"Video\\Intro\\pacman414.bmp"}, {"Video\\Intro\\pacman415.bmp"}, {"Video\\Intro\\pacman416.bmp"}, {"Video\\Intro\\pacman417.bmp"}
};

char pacdiel[100][40]=
{
{"Pics\\Die\\Left\\die1.bmp"}, {"Pics\\Die\\Left\\die2.bmp"}, {"Pics\\Die\\Left\\die3.bmp"}, {"Pics\\Die\\Left\\die4.bmp"}, {"Pics\\Die\\Left\\die5.bmp"}, {"Pics\\Die\\Left\\die6.bmp"}, {"Pics\\Die\\Left\\die7.bmp"}, {"Pics\\Die\\Left\\die8.bmp"}, {"Pics\\Die\\Left\\die9.bmp"}, {"Pics\\Die\\Left\\die10.bmp"},
{"Pics\\Die\\Left\\die11.bmp"}, {"Pics\\Die\\Left\\die12.bmp"}, {"Pics\\Die\\Left\\die13.bmp"}, {"Pics\\Die\\Left\\die14.bmp"}, {"Pics\\Die\\Left\\die15.bmp"}, {"Pics\\Die\\Left\\die16.bmp"}, {"Pics\\Die\\Left\\die17.bmp"}, {"Pics\\Die\\Left\\die18.bmp"}, {"Pics\\Die\\Left\\die19.bmp"}, {"Pics\\Die\\Left\\die20.bmp"},
{"Pics\\Die\\Left\\die21.bmp"}, {"Pics\\Die\\Left\\die22.bmp"}, {"Pics\\Die\\Left\\die23.bmp"}, {"Pics\\Die\\Left\\die24.bmp"}, {"Pics\\Die\\Left\\die25.bmp"}, {"Pics\\Die\\Left\\die26.bmp"}, {"Pics\\Die\\Left\\die27.bmp"}, {"Pics\\Die\\Left\\die28.bmp"}, {"Pics\\Die\\Left\\die29.bmp"}, {"Pics\\Die\\Left\\die30.bmp"},
{"Pics\\Die\\Left\\die31.bmp"}, {"Pics\\Die\\Left\\die32.bmp"}, {"Pics\\Die\\Left\\die33.bmp"}, {"Pics\\Die\\Left\\die34.bmp"}, {"Pics\\Die\\Left\\die35.bmp"}, {"Pics\\Die\\Left\\die36.bmp"}, {"Pics\\Die\\Left\\die37.bmp"}, {"Pics\\Die\\Left\\die38.bmp"}, {"Pics\\Die\\Left\\die39.bmp"}, {"Pics\\Die\\Left\\die40.bmp"},
{"Pics\\Die\\Left\\die41.bmp"}, {"Pics\\Die\\Left\\die42.bmp"}, {"Pics\\Die\\Left\\die43.bmp"}, {"Pics\\Die\\Left\\die44.bmp"}, {"Pics\\Die\\Left\\die45.bmp"}, {"Pics\\Die\\Left\\die46.bmp"}, {"Pics\\Die\\Left\\die47.bmp"}, {"Pics\\Die\\Left\\die48.bmp"}, {"Pics\\Die\\Left\\die49.bmp"}, {"Pics\\Die\\Left\\die50.bmp"},
{"Pics\\Die\\Left\\die51.bmp"}, {"Pics\\Die\\Left\\die52.bmp"}, {"Pics\\Die\\Left\\die53.bmp"}, {"Pics\\Die\\Left\\die54.bmp"}, {"Pics\\Die\\Left\\die55.bmp"}, {"Pics\\Die\\Left\\die56.bmp"}, {"Pics\\Die\\Left\\die57.bmp"}, {"Pics\\Die\\Left\\die58.bmp"}, {"Pics\\Die\\Left\\die59.bmp"}, {"Pics\\Die\\Left\\die60.bmp"},
{"Pics\\Die\\Left\\die61.bmp"}, {"Pics\\Die\\Left\\die62.bmp"}, {"Pics\\Die\\Left\\die63.bmp"}, {"Pics\\Die\\Left\\die64.bmp"}, {"Pics\\Die\\Left\\die65.bmp"}, {"Pics\\Die\\Left\\die66.bmp"}, {"Pics\\Die\\Left\\die67.bmp"}, {"Pics\\Die\\Left\\die68.bmp"}, {"Pics\\Die\\Left\\die69.bmp"}, {"Pics\\Die\\Left\\die70.bmp"},
{"Pics\\Die\\Left\\die71.bmp"}, {"Pics\\Die\\Left\\die72.bmp"}, {"Pics\\Die\\Left\\die73.bmp"}
};

char pacdier[100][40]=
{
    {"Pics\\Die\\Right\\die1.bmp"}, {"Pics\\Die\\Right\\die2.bmp"}, {"Pics\\Die\\Right\\die3.bmp"}, {"Pics\\Die\\Right\\die4.bmp"}, {"Pics\\Die\\Right\\die5.bmp"}, {"Pics\\Die\\Right\\die6.bmp"}, {"Pics\\Die\\Right\\die7.bmp"}, {"Pics\\Die\\Right\\die8.bmp"}, {"Pics\\Die\\Right\\die9.bmp"}, {"Pics\\Die\\Right\\die10.bmp"},
{"Pics\\Die\\Right\\die11.bmp"}, {"Pics\\Die\\Right\\die12.bmp"}, {"Pics\\Die\\Right\\die13.bmp"}, {"Pics\\Die\\Right\\die14.bmp"}, {"Pics\\Die\\Right\\die15.bmp"}, {"Pics\\Die\\Right\\die16.bmp"}, {"Pics\\Die\\Right\\die17.bmp"}, {"Pics\\Die\\Right\\die18.bmp"}, {"Pics\\Die\\Right\\die19.bmp"}, {"Pics\\Die\\Right\\die20.bmp"},
{"Pics\\Die\\Right\\die21.bmp"}, {"Pics\\Die\\Right\\die22.bmp"}, {"Pics\\Die\\Right\\die23.bmp"}, {"Pics\\Die\\Right\\die24.bmp"}, {"Pics\\Die\\Right\\die25.bmp"}, {"Pics\\Die\\Right\\die26.bmp"}, {"Pics\\Die\\Right\\die27.bmp"}, {"Pics\\Die\\Right\\die28.bmp"}, {"Pics\\Die\\Right\\die29.bmp"}, {"Pics\\Die\\Right\\die30.bmp"},
{"Pics\\Die\\Right\\die31.bmp"}, {"Pics\\Die\\Right\\die32.bmp"}, {"Pics\\Die\\Right\\die33.bmp"}, {"Pics\\Die\\Right\\die34.bmp"}, {"Pics\\Die\\Right\\die35.bmp"}, {"Pics\\Die\\Right\\die36.bmp"}, {"Pics\\Die\\Right\\die37.bmp"}, {"Pics\\Die\\Right\\die38.bmp"}, {"Pics\\Die\\Right\\die39.bmp"}, {"Pics\\Die\\Right\\die40.bmp"},
{"Pics\\Die\\Right\\die41.bmp"}, {"Pics\\Die\\Right\\die42.bmp"}, {"Pics\\Die\\Right\\die43.bmp"}, {"Pics\\Die\\Right\\die44.bmp"}, {"Pics\\Die\\Right\\die45.bmp"}, {"Pics\\Die\\Right\\die46.bmp"}, {"Pics\\Die\\Right\\die47.bmp"}, {"Pics\\Die\\Right\\die48.bmp"}, {"Pics\\Die\\Right\\die49.bmp"}, {"Pics\\Die\\Right\\die50.bmp"},
{"Pics\\Die\\Right\\die51.bmp"}, {"Pics\\Die\\Right\\die52.bmp"}, {"Pics\\Die\\Right\\die53.bmp"}, {"Pics\\Die\\Right\\die54.bmp"}, {"Pics\\Die\\Right\\die55.bmp"}, {"Pics\\Die\\Right\\die56.bmp"}, {"Pics\\Die\\Right\\die57.bmp"}, {"Pics\\Die\\Right\\die58.bmp"}, {"Pics\\Die\\Right\\die59.bmp"}, {"Pics\\Die\\Right\\die60.bmp"},
{"Pics\\Die\\Right\\die61.bmp"}, {"Pics\\Die\\Right\\die62.bmp"}, {"Pics\\Die\\Right\\die63.bmp"}, {"Pics\\Die\\Right\\die64.bmp"}, {"Pics\\Die\\Right\\die65.bmp"}, {"Pics\\Die\\Right\\die66.bmp"}, {"Pics\\Die\\Right\\die67.bmp"}, {"Pics\\Die\\Right\\die68.bmp"}, {"Pics\\Die\\Right\\die69.bmp"}, {"Pics\\Die\\Right\\die70.bmp"},
{"Pics\\Die\\Right\\die71.bmp"}, {"Pics\\Die\\Right\\die72.bmp"}, {"Pics\\Die\\Right\\die73.bmp"}
};

char pacdieu[100][40]=
{
    {"Pics\\Die\\Up\\die1.bmp"}, {"Pics\\Die\\Up\\die2.bmp"}, {"Pics\\Die\\Up\\die3.bmp"}, {"Pics\\Die\\Up\\die4.bmp"}, {"Pics\\Die\\Up\\die5.bmp"}, {"Pics\\Die\\Up\\die6.bmp"}, {"Pics\\Die\\Up\\die7.bmp"}, {"Pics\\Die\\Up\\die8.bmp"}, {"Pics\\Die\\Up\\die9.bmp"}, {"Pics\\Die\\Up\\die10.bmp"},
{"Pics\\Die\\Up\\die11.bmp"}, {"Pics\\Die\\Up\\die12.bmp"}, {"Pics\\Die\\Up\\die13.bmp"}, {"Pics\\Die\\Up\\die14.bmp"}, {"Pics\\Die\\Up\\die15.bmp"}, {"Pics\\Die\\Up\\die16.bmp"}, {"Pics\\Die\\Up\\die17.bmp"}, {"Pics\\Die\\Up\\die18.bmp"}, {"Pics\\Die\\Up\\die19.bmp"}, {"Pics\\Die\\Up\\die20.bmp"},
{"Pics\\Die\\Up\\die21.bmp"}, {"Pics\\Die\\Up\\die22.bmp"}, {"Pics\\Die\\Up\\die23.bmp"}, {"Pics\\Die\\Up\\die24.bmp"}, {"Pics\\Die\\Up\\die25.bmp"}, {"Pics\\Die\\Up\\die26.bmp"}, {"Pics\\Die\\Up\\die27.bmp"}, {"Pics\\Die\\Up\\die28.bmp"}, {"Pics\\Die\\Up\\die29.bmp"}, {"Pics\\Die\\Up\\die30.bmp"},
{"Pics\\Die\\Up\\die31.bmp"}, {"Pics\\Die\\Up\\die32.bmp"}, {"Pics\\Die\\Up\\die33.bmp"}, {"Pics\\Die\\Up\\die34.bmp"}, {"Pics\\Die\\Up\\die35.bmp"}, {"Pics\\Die\\Up\\die36.bmp"}, {"Pics\\Die\\Up\\die37.bmp"}, {"Pics\\Die\\Up\\die38.bmp"}, {"Pics\\Die\\Up\\die39.bmp"}, {"Pics\\Die\\Up\\die40.bmp"},
{"Pics\\Die\\Up\\die41.bmp"}, {"Pics\\Die\\Up\\die42.bmp"}, {"Pics\\Die\\Up\\die43.bmp"}, {"Pics\\Die\\Up\\die44.bmp"}, {"Pics\\Die\\Up\\die45.bmp"}, {"Pics\\Die\\Up\\die46.bmp"}, {"Pics\\Die\\Up\\die47.bmp"}, {"Pics\\Die\\Up\\die48.bmp"}, {"Pics\\Die\\Up\\die49.bmp"}, {"Pics\\Die\\Up\\die50.bmp"},
{"Pics\\Die\\Up\\die51.bmp"}, {"Pics\\Die\\Up\\die52.bmp"}, {"Pics\\Die\\Up\\die53.bmp"}, {"Pics\\Die\\Up\\die54.bmp"}, {"Pics\\Die\\Up\\die55.bmp"}, {"Pics\\Die\\Up\\die56.bmp"}, {"Pics\\Die\\Up\\die57.bmp"}, {"Pics\\Die\\Up\\die58.bmp"}, {"Pics\\Die\\Up\\die59.bmp"}, {"Pics\\Die\\Up\\die60.bmp"},
{"Pics\\Die\\Up\\die61.bmp"}, {"Pics\\Die\\Up\\die62.bmp"}, {"Pics\\Die\\Up\\die63.bmp"}, {"Pics\\Die\\Up\\die64.bmp"}, {"Pics\\Die\\Up\\die65.bmp"}, {"Pics\\Die\\Up\\die66.bmp"}, {"Pics\\Die\\Up\\die67.bmp"}, {"Pics\\Die\\Up\\die68.bmp"}, {"Pics\\Die\\Up\\die69.bmp"}, {"Pics\\Die\\Up\\die70.bmp"},
{"Pics\\Die\\Up\\die71.bmp"}, {"Pics\\Die\\Up\\die72.bmp"}, {"Pics\\Die\\Up\\die73.bmp"}
};

char pacdieD[100][40]=
{
    {"Pics\\Die\\Down\\die1.bmp"}, {"Pics\\Die\\Down\\die2.bmp"}, {"Pics\\Die\\Down\\die3.bmp"}, {"Pics\\Die\\Down\\die4.bmp"}, {"Pics\\Die\\Down\\die5.bmp"}, {"Pics\\Die\\Down\\die6.bmp"}, {"Pics\\Die\\Down\\die7.bmp"}, {"Pics\\Die\\Down\\die8.bmp"}, {"Pics\\Die\\Down\\die9.bmp"}, {"Pics\\Die\\Down\\die10.bmp"},
{"Pics\\Die\\Down\\die11.bmp"}, {"Pics\\Die\\Down\\die12.bmp"}, {"Pics\\Die\\Down\\die13.bmp"}, {"Pics\\Die\\Down\\die14.bmp"}, {"Pics\\Die\\Down\\die15.bmp"}, {"Pics\\Die\\Down\\die16.bmp"}, {"Pics\\Die\\Down\\die17.bmp"}, {"Pics\\Die\\Down\\die18.bmp"}, {"Pics\\Die\\Down\\die19.bmp"}, {"Pics\\Die\\Down\\die20.bmp"},
{"Pics\\Die\\Down\\die21.bmp"}, {"Pics\\Die\\Down\\die22.bmp"}, {"Pics\\Die\\Down\\die23.bmp"}, {"Pics\\Die\\Down\\die24.bmp"}, {"Pics\\Die\\Down\\die25.bmp"}, {"Pics\\Die\\Down\\die26.bmp"}, {"Pics\\Die\\Down\\die27.bmp"}, {"Pics\\Die\\Down\\die28.bmp"}, {"Pics\\Die\\Down\\die29.bmp"}, {"Pics\\Die\\Down\\die30.bmp"},
{"Pics\\Die\\Down\\die31.bmp"}, {"Pics\\Die\\Down\\die32.bmp"}, {"Pics\\Die\\Down\\die33.bmp"}, {"Pics\\Die\\Down\\die34.bmp"}, {"Pics\\Die\\Down\\die35.bmp"}, {"Pics\\Die\\Down\\die36.bmp"}, {"Pics\\Die\\Down\\die37.bmp"}, {"Pics\\Die\\Down\\die38.bmp"}, {"Pics\\Die\\Down\\die39.bmp"}, {"Pics\\Die\\Down\\die40.bmp"},
{"Pics\\Die\\Down\\die41.bmp"}, {"Pics\\Die\\Down\\die42.bmp"}, {"Pics\\Die\\Down\\die43.bmp"}, {"Pics\\Die\\Down\\die44.bmp"}, {"Pics\\Die\\Down\\die45.bmp"}, {"Pics\\Die\\Down\\die46.bmp"}, {"Pics\\Die\\Down\\die47.bmp"}, {"Pics\\Die\\Down\\die48.bmp"}, {"Pics\\Die\\Down\\die49.bmp"}, {"Pics\\Die\\Down\\die50.bmp"},
{"Pics\\Die\\Down\\die51.bmp"}, {"Pics\\Die\\Down\\die52.bmp"}, {"Pics\\Die\\Down\\die53.bmp"}, {"Pics\\Die\\Down\\die54.bmp"}, {"Pics\\Die\\Down\\die55.bmp"}, {"Pics\\Die\\Down\\die56.bmp"}, {"Pics\\Die\\Down\\die57.bmp"}, {"Pics\\Die\\Down\\die58.bmp"}, {"Pics\\Die\\Down\\die59.bmp"}, {"Pics\\Die\\Down\\die60.bmp"},
{"Pics\\Die\\Down\\die61.bmp"}, {"Pics\\Die\\Down\\die62.bmp"}, {"Pics\\Die\\Down\\die63.bmp"}, {"Pics\\Die\\Down\\die64.bmp"}, {"Pics\\Die\\Down\\die65.bmp"}, {"Pics\\Die\\Down\\die66.bmp"}, {"Pics\\Die\\Down\\die67.bmp"}, {"Pics\\Die\\Down\\die68.bmp"}, {"Pics\\Die\\Down\\die69.bmp"}, {"Pics\\Die\\Down\\die70.bmp"},
{"Pics\\Die\\Down\\die71.bmp"}, {"Pics\\Die\\Down\\die72.bmp"}, {"Pics\\Die\\Down\\die73.bmp"}
};

char raidie[100][40]=
{
    {"Pics\\Die\\Rai\\raidie1.bmp"}, {"Pics\\Die\\Rai\\raidie2.bmp"}, {"Pics\\Die\\Rai\\raidie3.bmp"}, {"Pics\\Die\\Rai\\raidie4.bmp"}, {"Pics\\Die\\Rai\\raidie5.bmp"}, {"Pics\\Die\\Rai\\raidie6.bmp"}, {"Pics\\Die\\Rai\\raidie7.bmp"}, {"Pics\\Die\\Rai\\raidie8.bmp"}, {"Pics\\Die\\Rai\\raidie9.bmp"}, {"Pics\\Die\\Rai\\raidie10.bmp"},
{"Pics\\Die\\Rai\\raidie11.bmp"}, {"Pics\\Die\\Rai\\raidie12.bmp"}, {"Pics\\Die\\Rai\\raidie13.bmp"}, {"Pics\\Die\\Rai\\raidie14.bmp"}, {"Pics\\Die\\Rai\\raidie15.bmp"}, {"Pics\\Die\\Rai\\raidie16.bmp"}, {"Pics\\Die\\Rai\\raidie17.bmp"}, {"Pics\\Die\\Rai\\raidie18.bmp"}, {"Pics\\Die\\Rai\\raidie19.bmp"}, {"Pics\\Die\\Rai\\raidie20.bmp"},
{"Pics\\Die\\Rai\\raidie21.bmp"}, {"Pics\\Die\\Rai\\raidie22.bmp"}, {"Pics\\Die\\Rai\\raidie23.bmp"}, {"Pics\\Die\\Rai\\raidie24.bmp"}, {"Pics\\Die\\Rai\\raidie25.bmp"}, {"Pics\\Die\\Rai\\raidie26.bmp"}, {"Pics\\Die\\Rai\\raidie27.bmp"}, {"Pics\\Die\\Rai\\raidie28.bmp"}, {"Pics\\Die\\Rai\\raidie29.bmp"}, {"Pics\\Die\\Rai\\raidie30.bmp"},
{"Pics\\Die\\Rai\\raidie31.bmp"}, {"Pics\\Die\\Rai\\raidie32.bmp"}, {"Pics\\Die\\Rai\\raidie33.bmp"}, {"Pics\\Die\\Rai\\raidie34.bmp"}, {"Pics\\Die\\Rai\\raidie35.bmp"}, {"Pics\\Die\\Rai\\raidie36.bmp"}, {"Pics\\Die\\Rai\\raidie37.bmp"}, {"Pics\\Die\\Rai\\raidie38.bmp"}, {"Pics\\Die\\Rai\\raidie39.bmp"}, {"Pics\\Die\\Rai\\raidie40.bmp"},
{"Pics\\Die\\Rai\\raidie41.bmp"}, {"Pics\\Die\\Rai\\raidie42.bmp"}, {"Pics\\Die\\Rai\\raidie43.bmp"}, {"Pics\\Die\\Rai\\raidie44.bmp"}, {"Pics\\Die\\Rai\\raidie45.bmp"}, {"Pics\\Die\\Rai\\raidie46.bmp"}, {"Pics\\Die\\Rai\\raidie47.bmp"}, {"Pics\\Die\\Rai\\raidie48.bmp"}, {"Pics\\Die\\Rai\\raidie49.bmp"}
};

char cookdie[100][40]=
{
    {"Pics\\Die\\CM\\cookdie1.bmp"}, {"Pics\\Die\\CM\\cookdie2.bmp"}, {"Pics\\Die\\CM\\cookdie3.bmp"}, {"Pics\\Die\\CM\\cookdie4.bmp"}, {"Pics\\Die\\CM\\cookdie5.bmp"}, {"Pics\\Die\\CM\\cookdie6.bmp"}, {"Pics\\Die\\CM\\cookdie7.bmp"}, {"Pics\\Die\\CM\\cookdie8.bmp"}, {"Pics\\Die\\CM\\cookdie9.bmp"}, {"Pics\\Die\\CM\\cookdie10.bmp"},
{"Pics\\Die\\CM\\cookdie11.bmp"}, {"Pics\\Die\\CM\\cookdie12.bmp"}, {"Pics\\Die\\CM\\cookdie13.bmp"}, {"Pics\\Die\\CM\\cookdie14.bmp"}, {"Pics\\Die\\CM\\cookdie15.bmp"}, {"Pics\\Die\\CM\\cookdie16.bmp"}, {"Pics\\Die\\CM\\cookdie17.bmp"}, {"Pics\\Die\\CM\\cookdie18.bmp"}, {"Pics\\Die\\CM\\cookdie19.bmp"}, {"Pics\\Die\\CM\\cookdie20.bmp"},
{"Pics\\Die\\CM\\cookdie21.bmp"}, {"Pics\\Die\\CM\\cookdie22.bmp"}, {"Pics\\Die\\CM\\cookdie23.bmp"}, {"Pics\\Die\\CM\\cookdie24.bmp"}, {"Pics\\Die\\CM\\cookdie25.bmp"}, {"Pics\\Die\\CM\\cookdie26.bmp"}, {"Pics\\Die\\CM\\cookdie27.bmp"}, {"Pics\\Die\\CM\\cookdie28.bmp"}, {"Pics\\Die\\CM\\cookdie29.bmp"}, {"Pics\\Die\\CM\\cookdie30.bmp"},
{"Pics\\Die\\CM\\cookdie31.bmp"}, {"Pics\\Die\\CM\\cookdie32.bmp"}, {"Pics\\Die\\CM\\cookdie33.bmp"}, {"Pics\\Die\\CM\\cookdie34.bmp"}, {"Pics\\Die\\CM\\cookdie35.bmp"}, {"Pics\\Die\\CM\\cookdie36.bmp"}, {"Pics\\Die\\CM\\cookdie37.bmp"}, {"Pics\\Die\\CM\\cookdie38.bmp"}, {"Pics\\Die\\CM\\cookdie39.bmp"}, {"Pics\\Die\\CM\\cookdie40.bmp"},
{"Pics\\Die\\CM\\cookdie41.bmp"}, {"Pics\\Die\\CM\\cookdie42.bmp"}, {"Pics\\Die\\CM\\cookdie43.bmp"}, {"Pics\\Die\\CM\\cookdie44.bmp"}, {"Pics\\Die\\CM\\cookdie45.bmp"}, {"Pics\\Die\\CM\\cookdie46.bmp"}, {"Pics\\Die\\CM\\cookdie47.bmp"}, {"Pics\\Die\\CM\\cookdie48.bmp"}, {"Pics\\Die\\CM\\cookdie49.bmp"}, {"Pics\\Die\\CM\\cookdie50.bmp"},
{"Pics\\Die\\CM\\cookdie51.bmp"}, {"Pics\\Die\\CM\\cookdie52.bmp"}, {"Pics\\Die\\CM\\cookdie53.bmp"}, {"Pics\\Die\\CM\\cookdie54.bmp"}, {"Pics\\Die\\CM\\cookdie55.bmp"}, {"Pics\\Die\\CM\\cookdie56.bmp"}, {"Pics\\Die\\CM\\cookdie57.bmp"}, {"Pics\\Die\\CM\\cookdie58.bmp"}, {"Pics\\Die\\CM\\cookdie59.bmp"}, {"Pics\\Die\\CM\\cookdie60.bmp"}
};

#endif // VIDEOS_H_INCLUDED
